faiss_db:
  collection_name: "document_portal"


embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

retriever:
  top_k: 10

llm:
  openai:
    provider: "openai"
    model_name: "gpt-4o-mini"
    temperature: 0
    max_output_tokens: 2048
  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"
    temperature: 0
    max_output_tokens: 2048

  google:
    provider: "google"
    model_name: "gemini-2.0-flash"
    temperature: 0
    max_output_tokens: 2048

multimodal:
  enabled: false
  provider: "openai" # vision provider: "openai" | "groq" | "google"
  vision_model: "gpt-4o-mini"
  hires_strategy: true # use unstructured partition strategy="hi_res"
  max_images: 5 # Groq vision supports up to 5 images per request
