# .github/workflows/ci.yml
name: Run Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ENV: local
      STRICT_API_KEYS: "false"
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
          cache-dependency-path: requirements-ci.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt

      - name: Run unit tests
        run: pytest tests/

  deepeval:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: |
            requirements-ci.txt
            requirements-deepeval.txt

      - name: Install deps (DeepEval only)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-deepeval.txt

      - name: Run DeepEval (non-blocking)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          CONFIDENT_API_KEY: ${{ secrets.CONFIDENT_API_KEY }}
          DEEPEVAL_INPUT_DIR: data_deep_eval
          DEEPEVAL_DATASET_ALIAS: test_doc_chat
        run: python eval/run_doc_chat_deepeval.py

  deepeval-mm:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install system deps for multimodal PDF parsing
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils tesseract-ocr libtesseract-dev libgl1 libmagic1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: |
            requirements-ci.txt
            requirements-deepeval.txt

      - name: Install deps (DeepEval only)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-deepeval.txt

      - name: Run DeepEval MM (non-blocking)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          CONFIDENT_API_KEY: ${{ secrets.CONFIDENT_API_KEY }}
          DEEPEVAL_INPUT_DIR: data_deep_eval
          DEEPEVAL_DATASET_ALIAS: test_doc_chat_mm
        run: python eval/run_mm_doc_chat_deepeval.py
